<?php if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5d6c2d16a7804',
	'title' => 'Footer',
	'fields' => array(
		array(
			'key' => 'field_5d6c2f464f63a',
			'label' => 'Footer Content',
			'name' => 'footer_content',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5d6c2f464f63b',
					'label' => 'Footer Text Toggle',
					'name' => 'footer_text_toggle',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'hide_admin' => 0,
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => 'Active',
					'ui_off_text' => 'Inactive',
				),
				array(
					'key' => 'field_5d6c2f464f63c',
					'label' => 'Footer Text',
					'name' => 'footer_text',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'hide_admin' => 0,
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
			),
		),
		array(
			'key' => 'field_5d6c2e2a00dee',
			'label' => 'Footer Credit',
			'name' => 'footer_credit',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5d6c2e4200def',
					'label' => 'Footer Credit Toggle',
					'name' => 'footer_credit_toggle',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'hide_admin' => 0,
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => 'Active',
					'ui_off_text' => 'Inactive',
				),
				array(
					'key' => 'field_5d6c2e6f00df0',
					'label' => 'Footer Credit',
					'name' => 'footer_credit',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'hide_admin' => 0,
					'default_value' => 'Website by Mark Salt',
					'placeholder' => 'Website by Mark Salt',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_5d6c2e8600df1',
			'label' => 'Footer Copyright',
			'name' => 'footer_copyright',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5d6c2e9400df2',
					'label' => 'Footer Copyright Toggle',
					'name' => 'footer_copyright_toggle',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'hide_admin' => 0,
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => 'Active',
					'ui_off_text' => 'Inactive',
				),
				array(
					'key' => 'field_5d6c2fd875e9d',
					'label' => 'Footer Copyright Year Toggle',
					'name' => 'footer_copyright_year_toggle',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'hide_admin' => 0,
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => 'Active',
					'ui_off_text' => 'Inactive',
				),
				array(
					'key' => 'field_5d6c2eac00df3',
					'label' => 'Footer Copyright Text',
					'name' => 'footer_copyright_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'hide_admin' => 0,
					'default_value' => 'Company Name',
					'placeholder' => 'Company Name',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-theme-extras',
			),
		),
	),
	'menu_order' => 300,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;
?>